# -*- coding: utf-8 -*-
"""NVIDIA driver installation engine.

How it works: for the selected method (nvk / repo / run) and distribution
family, ONE bash script is generated and run via pkexec — the user enters
the password only once. The script prints markers:
    @STEP@ desc   — start of the next step (the GUI updates the progress bar)
    @ERROR@ desc   — human-readable error description before aborting
    @SUCCESS@      — all steps finished
The entire output goes to the live log in the GUI and to the installation
history file.
"""
from __future__ import annotations

import os
import subprocess
import tempfile
from dataclasses import dataclass

try:
    from PySide6.QtCore import QThread, Signal
except ImportError:
    # The CLI version (a separate project) imports build_plan and _ROOT_RUNNER
    # from here without Qt installed — the stubs allow the module to load, and
    # the InstallThread class simply isn't used then (the GUI always has PySide6)
    QThread = object

    def Signal(*_args, **_kwargs):  # noqa: N802 — Qt API stub
        return None

from app.i18n import tr, tr_prefix

from . import gpu, history, nvidia_versions, utils
from .distro import DistroInfo


@dataclass
class InstallOptions:
    """Installation parameters chosen by the user in the GUI."""

    method: str                 # "nvk" | "repo" | "run"
    distro: DistroInfo
    open_modules: bool = False  # open kernel modules (Turing+)
    run_version: str = ""       # version for the "run" method, e.g. "580.95.05"
    repo_package: str = ""      # package for Kubuntu/Mint, e.g. "nvidia-driver-580"
    repo_source: str = ""       # plain Debian: "debian" (non-free) | "nvidia"
    use_backports: bool = False  # NVK on plain Debian with RTX 50xx
    boot_report: bool = False   # boot report service (opt-in from Settings)
    snapshot: bool = False      # Timeshift snapshot first (opt-in, install page)
    gpu_name: str = ""          # detected card model — G0X generation pick on openSUSE
    gpu_pci_id: str = ""        # PCI device ID (e.g. "2c05") — fallback when the name is generic


# Runs a script supplied on standard input (the pkexec path).
# Root rewrites the script from the pipe into its OWN temporary file (0600,
# root) and only then executes it — the contents cannot be swapped between
# authorization and execution (TOCTOU), as they could with a user file in
# /tmp. Executing from a file (not `bash -s`) leaves stdin at EOF, so no step
# will "eat" the rest of the script if it happens to read standard input.
_ROOT_RUNNER = (
    'tmp="$(mktemp)" && cat > "$tmp" && bash "$tmp"; rc=$?; rm -f "$tmp"; exit $rc'
)

# Header of every generated script — helper functions and non-interactive mode
_SCRIPT_HEADER = """#!/bin/bash
# Script generated automatically by NVIDIA Driver Installer.
set -o pipefail
export DEBIAN_FRONTEND=noninteractive
step() { echo "@STEP@ $1"; }
error() { echo "@ERROR@ $1"; exit 1; }
"""

# modprobe configuration for the NVIDIA driver: nouveau blacklist + KMS (Wayland)
_MODPROBE_CONFIG = """mkdir -p /etc/modprobe.d
cat > /etc/modprobe.d/blacklist-nouveau.conf <<'EOF'
# Generated by NVIDIA Driver Installer - nouveau driver blacklist
blacklist nouveau
options nouveau modeset=0
EOF
cat > /etc/modprobe.d/nvidia-modeset.conf <<'EOF'
# Generated by NVIDIA Driver Installer - KMS for NVIDIA (Wayland)
options nvidia_drm modeset=1 fbdev=1
EOF
true"""

# Removes our configuration (for the NVK method, where nouveau should work).
# Additionally: orphaned dracut files forcing nvidia modules into initramfs
# (force_drivers/add_drivers) — left behind by distribution tools
# (e.g. nvidia-inst on EndeavourOS creates /etc/dracut.conf.d/eos_nvidia_open.conf,
# which no package or hook cleans up; the EndeavourOS 2026-07-05 case).
# After the driver is uninstalled such a file tells dracut to force nonexistent
# modules (FAILED during build) and writes rd.driver.pre=nvidia into the
# initramfs cmdline — load errors on every boot. We only remove files whose
# content actually forces nvidia modules (conditioned on system state, not the
# distribution name); without such files the loop changes nothing.
#
# The same problem on the Debian side comes from /etc/initramfs-tools/modules:
# the nvidia packages list the modules there so that they land in the initramfs.
# Once the driver is gone the entries remain and every initramfs rebuild spits
# out "could not get modinfo from 'nvidia'" plus libkmod errors, for each
# installed kernel — Ubuntu 26.04 (dracut as the initramfs-tools backend),
# 2026-08-11. Only whole lines with our four modules are removed, so entries
# added by the user survive; without the file the step changes nothing.
_REMOVE_MODPROBE_CONFIG = (
    "rm -f /etc/modprobe.d/blacklist-nouveau.conf"
    " /etc/modprobe.d/nvidia-modeset.conf"
    " /etc/modprobe.d/nvidia-drm.conf"
    " /etc/modprobe.d/nvidia-installer-disable-nouveau.conf"
    " /usr/lib/modprobe.d/nvidia-installer-disable-nouveau.conf\n"
    "for f in /etc/dracut.conf.d/*.conf; do\n"
    '  [ -e "$f" ] || continue\n'
    "  if grep -qE '^[^#]*(force_drivers|add_drivers)[+ ]?=.*nvidia' \"$f\"; then\n"
    '    echo "Removing NVIDIA module forcing in the dracut configuration: $f"\n'
    '    rm -f "$f"\n'
    "  fi\n"
    "done\n"
    "MODLIST=/etc/initramfs-tools/modules\n"
    "NVMOD='^[[:space:]]*nvidia(_drm|_modeset|_uvm)?([[:space:]].*)?$'\n"
    'if [ -f "$MODLIST" ] && grep -qE "$NVMOD" "$MODLIST"; then\n'
    '  echo "Removing NVIDIA module entries from $MODLIST"\n'
    '  sed -i -E "/$NVMOD/d" "$MODLIST"\n'
    "fi\n"
    "true"
)

# Removes NVIDIA driver forcing in environment variables — left behind by
# other tools (e.g. nvidia-driver-manager). Without the NVIDIA driver they
# break EGL initialization and the desktop falls back to CPU software rendering
_REMOVE_GL_ENV = """rm -f /etc/environment.d/99-nvidia-wayland.conf
if [ -f /etc/environment ]; then
  sed -i -E '/^(GBM_BACKEND|__GLX_VENDOR_LIBRARY_NAME|__EGL_VENDOR_LIBRARY_FILENAMES|__EGL_VENDOR_LIBRARY_FILELIST|LIBVA_DRIVER_NAME|VDPAU_DRIVER)=.*nvidia/d' /etc/environment
fi
true"""

# Removes nvidia-drm parameters from the kernel command line — a leftover from
# the proprietary driver. A non-critical step: errors don't abort the installation
_REMOVE_KERNEL_PARAMS = """if [ -f /etc/default/grub ] && grep -qE 'nvidia[-_]drm\\.' /etc/default/grub; then
  sed -i -E 's/ ?nvidia[-_]drm\\.[a-z]+=[0-9]+//g' /etc/default/grub
  if command -v update-grub >/dev/null 2>&1; then update-grub || true
  elif command -v grub2-mkconfig >/dev/null 2>&1; then grub2-mkconfig -o /boot/grub2/grub.cfg || true
  elif command -v grub-mkconfig >/dev/null 2>&1; then grub-mkconfig -o /boot/grub/grub.cfg || true
  fi
fi
if command -v grubby >/dev/null 2>&1; then
  grubby --update-kernel=ALL --remove-args="nvidia-drm.modeset=1 nvidia-drm.fbdev=1 nvidia_drm.modeset=1 nvidia_drm.fbdev=1" 2>/dev/null || true
fi
true"""

# Checks for GSP firmware presence — without it nouveau won't drive RTX cards
# (Turing and newer); only a warning, on older cards GSP does not exist
_GSP_FIRMWARE_CHECK = (
    "find /lib/firmware/nvidia -name 'gsp*' 2>/dev/null | grep -q ."
    ' || echo "WARNING: no GSP firmware files in /lib/firmware/nvidia'
    ' — on RTX cards nouveau will not start"\ntrue'
)

# Checks for the nouveau module for the running kernel — without it, after the
# NVIDIA driver is uninstalled the desktop falls back to CPU rendering
_NOUVEAU_MODULE_CHECK = (
    "modinfo nouveau >/dev/null 2>&1"
    ' || echo "WARNING: no nouveau module for the running kernel'
    ' — the desktop may fall back to CPU software rendering"\ntrue'
)

# Fedora: the nouveau module lives in the kernel-modules package, which may be
# missing — installing akmod-nvidia can pull in a new kernel only partially
# (kernel-core and kernel-devel as dependencies, without kernel-modules). After
# switching to NVK such a kernel comes up with no GPU driver at all. Install
# kernel-modules for every installed kernel that is missing nouveau.
_NOUVEAU_KERNEL_MODULES_FEDORA = """for k in /lib/modules/*/; do
  k="$(basename "$k")"
  [ -e "/lib/modules/$k/vmlinuz" ] || continue
  modinfo -k "$k" nouveau >/dev/null 2>&1 && continue
  dnf -y install "kernel-modules-$k" || echo "WARNING: failed to install the kernel-modules-$k package"
done
true"""

# Nobara: its own repository (nobara-nvidia-production) provides akmod-nvidia
# in a version newer than RPMFusion, but userspace is packaged the negativo17
# way (nvidia-driver*), not the RPMFusion way (xorg-x11-drv-nvidia*). The fixed
# list "akmod-nvidia xorg-x11-drv-nvidia-cuda" then mixes two stacks: the kernel
# module comes from the distribution repo (the higher version wins), the CUDA
# libraries from RPMFusion (the only provider of that name), and the actual GL
# driver (libGLX_nvidia) is not installed at all — the desktop falls back to
# llvmpipe, nvidia-smi reports "Driver/library version mismatch" (the Nobara 43
# case, 2026-07-03). We condition the package set on the repository state, not
# the distribution name: if the latest akmod-nvidia has an nvidia-driver
# counterpart in the same version, and xorg-x11-drv-nvidia in that version does
# not exist, we install the native set (first removing any xorg-x11-drv-nvidia*
# leftovers — the same files under different package names cause conflicts). On
# plain Fedora nvidia-driver does not exist in any repository, the condition
# does not hold and the set stays exactly as before.
_FEDORA_REPO_INSTALL = """PKGS="akmod-nvidia xorg-x11-drv-nvidia-cuda"
AKMOD_V="$(dnf -q repoquery --qf '%{version}\\n' akmod-nvidia 2>/dev/null | sort -V | tail -n1)"
if [ -n "$AKMOD_V" ] \\
   && dnf -q repoquery --qf '%{version}\\n' nvidia-driver 2>/dev/null | grep -qxF "$AKMOD_V" \\
   && ! dnf -q repoquery --qf '%{version}\\n' xorg-x11-drv-nvidia 2>/dev/null | grep -qxF "$AKMOD_V"; then
  echo "The distribution repository packages the driver as nvidia-driver ($AKMOD_V) — installing the native set"
  PKGS="akmod-nvidia nvidia-driver nvidia-driver-cuda"
  dnf -y remove 'xorg-x11-drv-nvidia*' 2>/dev/null || true
fi
dnf -y install $PKGS || error "Instalacja pakietów nie powiodła się\""""

# openSUSE: the driver generation (G06, G07, ...) changes over time — NVIDIA
# retires architectures into legacy generations, so a hardcoded name would rot.
# openSUSE driver generations (G0X) are driver BRANCHES with overlapping,
# mutually exclusive card ranges — the newest generation present in the repo
# is NOT automatically right for the card (G07 = Turing+ only; a Pascal card
# offered G07 would get a driver that does not support it). The allowed list
# is therefore computed from the DETECTED CARD's architecture (gpu.py) and
# only then narrowed by repository availability, newest first. zypper's own
# modalias autoselection (`zypper inr`) was verified on live Tumbleweed
# 2026-07-15 and rejected: restricted to the NVIDIA repo it selects nothing
# (the signed kmp lives in the OSS repo), and unrestricted it picks the older
# G06 branch and drags in unrelated system recommends (snapper, btrfs tools).
# Unrecognized card names are treated like new cards (by far the most common
# case). Legacy architectures map 1:1 to their openSUSE generation
# (470→G05, 390→G04, 340→G03); if the repo no longer ships it, the loop ends
# in a clear error and such cards are steered to the legacy .run path anyway.
def _suse_generations(gpu_name: str, gpu_pci_id: str = "") -> list[str]:
    """G0X generations allowed for the detected card, newest first."""
    if not gpu_name or gpu.is_turing_or_newer(gpu_name, gpu_pci_id):
        return ["G09", "G08", "G07", "G06"]
    info = gpu.recommended_driver_info(gpu_name, gpu_pci_id)
    if info["max_major"] == 580:        # Maxwell/Pascal/Volta — G07+ excluded
        return ["G06"]
    legacy_gen = {"470": "G05", "390": "G04", "340": "G03"}.get(info["legacy"] or "")
    if legacy_gen:
        return [legacy_gen]
    # A non-empty name with an UNRECOGNIZED architecture (e.g. the placeholder
    # "NVIDIA (nieznany model, ID …)" when neither nvidia-smi nor vulkaninfo
    # could name the card) — treat like a new card, same as the empty name:
    # capping such a card at G06 would rot once cards outgrow the 580 branch.
    return ["G09", "G08", "G07", "G06"]


# openSUSE ships the driver packages with modalias supplements, so a plain
# `zypper dup` INSTALLS them by itself the moment an NVIDIA card is present and
# the NVIDIA repository is enabled (openSUSE-repos-*-NVIDIA enables it without
# being asked). Next to a .run installation that is a trap: the packages land
# beside it, the kmp is built only for the NEW kernel, while every library
# symlink still points at the .run version. The module and userspace then come
# from two different driver releases — EGL fails to initialize, the compositor
# crashes in a loop and the machine boots to a black screen. Verified on live
# Tumbleweed: .run 595.84 from July met packaged 580.178.04 from a September
# `dup` (see the "Usuwanie sterownika z pliku .run" step, which only guards the
# reverse order — our own repo installation).
#
# Locks are the openSUSE-sanctioned defence: a locked name is not pulled in by
# supplements and not updated. They are set right after a successful .run
# installation and lifted wherever we hand the card back to packages (repo
# method, NVK) or wipe the driver. Patterns are name globs, so they also cover
# generations that do not exist yet. libnvidia-egl-gbm1 / -egl-wayland1 are
# deliberately NOT locked — they are independent projects, not tied to the
# driver release, and locking them would block unrelated updates.
_SUSE_LOCK_PATTERNS = "'nvidia*' 'libnvidia-gpucomp*' 'x11-video-nvidia*'"

_SUSE_ADD_LOCKS = (
    f"zypper -n al {_SUSE_LOCK_PATTERNS} >/dev/null 2>&1 || true\n"
    'echo "NVIDIA packages locked in zypper — a system update will no longer'
    ' install a second driver next to the .run one."\n'
    'echo "To lift the lock: zypper rl \'nvidia*\' \'libnvidia-gpucomp*\''
    ' \'x11-video-nvidia*\'"'
)

# Lifting a lock that was never set is not an error for us — hence `|| true`
# and the silent output; without locks the step is a no-op.
_SUSE_REMOVE_LOCKS = f"zypper -n rl {_SUSE_LOCK_PATTERNS} >/dev/null 2>&1 || true"


# The generation comes from _suse_generations() (card architecture ceiling)
# narrowed by the repository state, per the official SDB:NVIDIA_drivers
# packaging: open kernel modules = nvidia-open-driver-G0X-signed-kmp-FLAVOR
# (signed for Secure Boot; in the openSUSE OSS repo), proprietary =
# nvidia-driver-G0X-kmp-FLAVOR (NVIDIA repo). Userspace for both:
# nvidia-video-G0X + nvidia-compute-utils-G0X (--recommends pulls in the GL
# libraries), and those live only in the NVIDIA repo.
#
# A generation is usable only when BOTH halves are present, and the two repos
# are not in step: Leap 16.0 ships the G07 open kmp but no nvidia-video-G07
# (userspace stops at G06), while on Tumbleweed the proprietary line stops at
# G06 even though G07 userspace exists. Picking the generation from one half
# alone therefore lands on a set that cannot be installed — hence one loop
# that accepts a generation only when its userspace AND a matching kmp exist.
#
# The kmp suffix is the kernel flavor (the tail of `uname -r`): kmp-default
# fits only kernel-default, and Tumbleweed also ships kernel-longterm, Leap
# 16.1 kernel-rt, Leap 15.6 kernel-azure — each with its own kmp. Installing
# kmp-default on such a system makes zypper drag in kernel-default instead of
# building for the running kernel. The exact flavor is tried first, then
# -kmp-meta (the variant SUSE recommends, which resolves the flavor itself but
# can be ambiguous between the cuda and non-cuda kmp), then -kmp-default as a
# last resort for an unusual flavor with no package of its own.
def _suse_repo_install(open_modules: bool, generations: list[str]) -> str:
    """zypper installation script: generation detection + the package set."""
    if open_modules:
        prefix, kmp_infix = "nvidia-open-driver", "signed-kmp"
        conflict = "'^nvidia-driver-G0[0-9]+-kmp'"
    else:
        prefix, kmp_infix = "nvidia-driver", "kmp"
        conflict = "'^nvidia-open-driver-'"
    kmp_candidates = " ".join(
        f'"{prefix}-$g-{kmp_infix}-{suffix}"'
        for suffix in ("${FLAVOR}", "meta", "default")
    )
    return (
        # flavor of the RUNNING kernel: "6.17.4-1-default" -> "default"
        'FLAVOR="$(uname -r)"; FLAVOR="${FLAVOR##*-}"\n'
        'GEN=""; KMP=""\n'
        f"for g in {' '.join(generations)}; do\n"
        # no userspace for this generation in the NVIDIA repo = unusable
        '  zypper -n se -x -t package "nvidia-video-$g" >/dev/null 2>&1'
        " || continue\n"
        f"  for k in {kmp_candidates}; do\n"
        '    if zypper -n se -x -t package "$k" >/dev/null 2>&1; then\n'
        '      GEN="$g"; KMP="$k"; break 2\n'
        "    fi\n"
        "  done\n"
        "done\n"
        '[ -n "$GEN" ] || error "Nie znaleziono pakietów sterownika NVIDIA w repozytoriach"\n'
        'echo "Detected driver generation: $GEN (kernel flavor: $FLAVOR)"\n'
        'echo "Kernel module package: $KMP"\n'
        # a leftover kernel module of the other flavor conflicts with the new
        # one (same files); on a system without it xargs gets nothing = no-op.
        # --qf '%{NAME}': zypper takes a capability (NAME[.ARCH][OP EDITION]),
        # so a bare `rpm -qa` line ("nvidia-video-G07-595.99.02-1.1.x86_64")
        # matches no package and the removal silently does nothing
        "rpm -qa --qf '%{NAME}\\n' | grep -E "
        f"{conflict} | xargs -r zypper -n rm || true\n"
        # NVIDIA userspace packages carry an EULA; in non-interactive mode
        # zypper answers the license prompt with its default "No" and aborts —
        # the flag accepts it, exactly as zypper's own abort message instructs
        # (live Tumbleweed, 2026-07-15)
        'zypper -n in --auto-agree-with-licenses --recommends'
        ' "$KMP" "nvidia-video-${GEN}"'
        ' "nvidia-compute-utils-${GEN}"'
        ' || error "Instalacja pakietów nie powiodła się"'
    )


# Kernel built with Clang and LTO (e.g. CachyOS with ThinLTO): the .run
# installer's own module build compiles LLVM bitcode (it detects CC itself from
# CONFIG_CC_VERSION_TEXT), but its Makefile has `LD ?= ld` and passes
# `"LD=$(LD)"` to kbuild, so linking is done by GNU ld and fails
# ("/usr/bin/ld: unrecognised emulation mode: llvm"). Thanks to `?=` the
# environment LD=ld.lld takes precedence; LLVM=1 switches the rest of the kbuild
# tools (llvm-ar/nm/objcopy), and IGNORE_CC_MISMATCH=1 disables the compiler
# version comparison, which is confused by the ", LLD" suffix in such a kernel's
# CONFIG_CC_VERSION_TEXT. The LLVM tools are guaranteed: the headers of a kernel
# built with Clang depend on clang/llvm/lld. dkms detects Clang kernels itself
# (grep CONFIG_CC_IS_CLANG per kernel), which is why we pass the variables via
# `env` only to the .run installer, and don't export them to further steps. On a
# kernel built with GCC (plain Arch, Debian, Fedora, Mint) the condition does
# not hold, NV_TOOLCHAIN_ENV stays empty and nothing changes.
_LLVM_KERNEL_ENV = """NV_TOOLCHAIN_ENV=""
if grep -qs '^CONFIG_CC_IS_CLANG=y' "/lib/modules/$(uname -r)/build/.config"; then
  echo "Kernel built with Clang/LLVM — the module will be built with the LLVM toolchain"
  NV_TOOLCHAIN_ENV="LLVM=1 LD=ld.lld OBJDUMP=llvm-objdump IGNORE_CC_MISMATCH=1"
fi"""

# The .run installer builds the DKMS module only for the running kernel. When
# GRUB boots a different kernel by default (e.g. installing from an older one
# while the newest is the default), the system would come up without a driver
# and without nouveau (blacklisted) — the desktop would fall back to CPU
# rendering. Build the module for every kernel that has headers.
_DKMS_ALL_KERNELS = """for k in /lib/modules/*/; do
  k="$(basename "$k")"
  [ "$k" = "$(uname -r)" ] && continue
  [ -e "/lib/modules/$k/build" ] || continue
  dkms autoinstall -k "$k" || echo "WARNING: building the DKMS module for kernel $k failed"
done
true"""

# Arch: fixing "ghost packages" — a package is listed in the pacman database,
# but its files were deleted from disk outside pacman (e.g. cleanup after a .run
# driver by another tool). `pacman -S --needed` won't touch such a package, and
# without the libnvidia-egl-* libraries the GBM EGL platform doesn't come up and
# the desktop falls back to a TTY, even though the installation and kernel
# module are correct (the CachyOS case, 2026-07-03: no libnvidia-egl-gbm.so.1
# with egl-gbm "installed"). On a healthy system the step only reads state
# (`pacman -Qk`) and changes nothing. The -Qk result is logged unconditionally
# for every package: on 2026-07-04 the step reported nothing in real runs
# despite files missing on disk — since then the installation log always
# documents the observed package state.
_ARCH_VERIFY_EGL_PACKAGES = """for p in nvidia-utils egl-gbm egl-wayland egl-wayland2 egl-x11 eglexternalplatform libglvnd; do
  if ! pacman -Qq "$p" >/dev/null 2>&1; then
    echo "Package $p: not installed"
    continue
  fi
  stan="$(LANG=C pacman -Qk "$p" 2>/dev/null)"
  echo "Package ${stan:-$p: pacman -Qk gave no response}"
  if echo "$stan" | grep -qE ', [1-9][0-9]* missing'; then
    echo "Package $p has missing files on disk — reinstalling"
    pacman -S --noconfirm "$p" || error "Naprawa pakietu nie powiodła się ($p)"
  fi
done
true"""

# Enables the non-free sections in plain Debian's APT sources (repo and firmware)
_DEBIAN_NONFREE_SECTIONS = (
    "if [ -f /etc/apt/sources.list.d/debian.sources ]; then\n"
    "  sed -i 's/^Components:.*/Components: main contrib non-free non-free-firmware/'"
    " /etc/apt/sources.list.d/debian.sources\nfi\n"
    "if [ -f /etc/apt/sources.list ]; then\n"
    "  sed -i '/^deb /{/non-free/!s/ main/ main contrib non-free non-free-firmware/}'"
    " /etc/apt/sources.list\nfi\n"
    'apt-get update || error "apt-get update nie powiodło się"'
)

# Removes the official NVIDIA repository — when returning to packages from the
# Debian repository, newer versions from the NVIDIA repo would shadow them
_REMOVE_NVIDIA_REPO = (
    "apt-get -y purge cuda-keyring 2>/dev/null || true\n"
    "rm -f /etc/apt/sources.list.d/cuda-debian*.list\ntrue"
)

# Detects the kernel package on Arch (linux / linux-lts / linux-cachyos etc.),
# to install the matching headers needed by DKMS
_ARCH_KERNEL_HEADERS = (
    'KERNEL_PKG="$(pacman -Qqo "/usr/lib/modules/$(uname -r)/vmlinuz"'
    ' 2>/dev/null || echo linux)"'
)


# System snapshot BEFORE any modification (opt-in: a checkbox on the install
# page, shown only when Timeshift is installed). Runs as the FIRST step of the
# plan, so a restore returns the system to the exact pre-installation state.
# Failure ABORTS the installation — the user explicitly requested the safety
# net, and continuing without it would silently defeat its purpose. The command
# still checks the actual state (timeshift binary present): the GUI hides the
# option without Timeshift, so the error branch only fires when the tool
# disappeared between the click and the script run.
_SNAPSHOT_STEP = (
    "Tworzenie migawki systemu (Timeshift — może potrwać kilka minut)",
    """command -v timeshift >/dev/null 2>&1 \\
  || error "Program Timeshift nie jest zainstalowany — zainstaluj go albo wyłącz opcję migawki"
timeshift --create --comments "NVIDIA Driver Installer" --scripted \\
  || error "Tworzenie migawki Timeshift nie powiodło się — szczegóły w logu powyżej\"""",
)

# Boot report: a systemd service that, after every system startup, writes
# graphics diagnostics (driver, modules, EGL consistency, journal errors) to
# the log directory of the user who launched the installer. The home directory
# usually lies outside the scope of system restore (Timeshift skips /home by
# default, a common layout with /home on a separate partition), so a report from
# a boot that ended in a black screen waits on disk after a snapshot restore —
# without it, restoring wipes the journal and package manager logs from the
# faulty boot. The step only writes files and enables a service that READS state
# — on no distribution does it change the graphics configuration (principle: a
# behavioral no-op). The service is OPT-IN (a checkbox in Settings, disabled by
# default): it stays on the system permanently, so it requires the user's
# informed consent. When the option is disabled, the installation instead runs a
# cleanup step (_BOOT_REPORT_REMOVE_STEP) that removes the service left by
# earlier installations.
_BOOT_REPORT_STEP = (
    "Włączanie raportu rozruchu (diagnostyka po restarcie)",
    r"""u="${PKEXEC_UID:-${SUDO_UID:-}}"
home=""
[ -n "$u" ] && home="$(getent passwd "$u" | cut -d: -f6)"
if [ -z "$home" ] || [ ! -d "$home" ]; then
  echo "Could not detect the user running the installer — skipping the boot report"
else
  install -d /usr/local/lib/nvidia-installer
  cat > /usr/local/lib/nvidia-installer/raport-rozruchu.sh <<'RAPORT'
#!/bin/bash
# Writes a graphics-state report from the current boot (state reads only).
sleep 25
d="$RAPORT_KATALOG"; [ -n "$d" ] || exit 0
mkdir -p "$d"
f="$d/raport-rozruchu-$(date +%Y%m%d-%H%M%S).txt"
{
  echo "=== Boot report $(date '+%F %T') | kernel: $(uname -r)"
  echo "--- cmdline: $(cat /proc/cmdline)"
  echo "--- GPU (lspci -nnk):"
  command -v lspci >/dev/null && lspci -nnk | grep -iA3 -E 'vga|3d controller'
  echo "--- nvidia/nouveau modules:"
  lsmod | grep -E '^(nvidia|nouveau)' || echo "(none loaded)"
  echo "--- nvidia-smi:"
  if command -v nvidia-smi >/dev/null; then timeout 10 nvidia-smi; else echo "(unavailable)"; fi
  echo "--- EGL libraries referenced by JSON files:"
  for j in /usr/share/egl/egl_external_platform.d/*.json /usr/share/glvnd/egl_vendor.d/*.json; do
    [ -e "$j" ] || continue
    lib="$(grep -o '"library_path"[[:space:]]*:[[:space:]]*"[^"]*"' "$j" | cut -d'"' -f4)"
    [ -n "$lib" ] || continue
    case "$lib" in
      /*) if [ -e "$lib" ]; then st="OK  "; else st="BRAK"; fi ;;
      *) if [ -e "/usr/lib/$lib" ] || ldconfig -p 2>/dev/null | grep -qF "$lib"; then st="OK  "; else st="BRAK"; fi ;;
    esac
    echo "$st $j -> $lib"
  done
  if command -v pacman >/dev/null; then
    echo "--- pacman -Qk of NVIDIA/EGL packages:"
    for p in nvidia-utils egl-gbm egl-wayland egl-wayland2 egl-x11 eglexternalplatform libglvnd; do
      pacman -Qq "$p" >/dev/null 2>&1 && LANG=C pacman -Qk "$p" 2>/dev/null
    done
  fi
  echo "--- kernel graphics errors in this boot:"
  journalctl -b -k -p err --no-pager 2>/dev/null | grep -iE 'nvrm|nvidia|nouveau|drm' | tail -30
  echo "--- compositor / graphics session:"
  journalctl -b --no-pager 2>/dev/null | grep -iE 'kwin|gnome-shell|mutter|Xorg|sddm|gdm' \
    | grep -iE 'fail|error|crash|segfault|core|EGL|DRI' | tail -30
} > "$f" 2>&1
chown "$RAPORT_WLASCICIEL" "$f" 2>/dev/null || true
ls -1t "$d"/raport-rozruchu-*.txt 2>/dev/null | tail -n +11 | xargs -r rm -f
RAPORT
  chmod 755 /usr/local/lib/nvidia-installer/raport-rozruchu.sh
  cat > /etc/systemd/system/nvidia-installer-raport.service <<UNIT
[Unit]
Description=NVIDIA Driver Installer boot report (graphics diagnostics)

[Service]
Type=simple
Environment=RAPORT_KATALOG=$home/.local/share/nvidia-installer-gui/raporty
Environment=RAPORT_WLASCICIEL=$u:$(id -g "$u")
ExecStart=/usr/local/lib/nvidia-installer/raport-rozruchu.sh

[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  if systemctl enable nvidia-installer-raport.service; then
    echo "Boot report: $home/.local/share/nvidia-installer-gui/raporty"
  else
    echo "WARNING: failed to enable the boot report service"
  fi
fi
true""",
)

# Cleans up the boot report service when the option is disabled in Settings —
# removes the service left by earlier installations (until 2026-07-05 it was
# enabled unconditionally). Conditioned on the actual system state (the service
# file exists); without it the step changes nothing (no-op on a clean system).
_BOOT_REPORT_REMOVE_STEP = (
    "Porządkowanie usługi raportu rozruchu (opcja wyłączona)",
    """if [ -f /etc/systemd/system/nvidia-installer-raport.service ]; then
  echo "Removing the boot report service from a previous installation"
  systemctl disable --now nvidia-installer-raport.service 2>/dev/null || true
  rm -f /etc/systemd/system/nvidia-installer-raport.service
  rm -rf /usr/local/lib/nvidia-installer
  systemctl daemon-reload
fi
true""",
)


def _removal_commands(family: str) -> str:
    """Commands to completely remove the NVIDIA driver (repo and .run)."""
    # A .run installation leaves its own uninstaller — use it first
    common = 'if [ -x /usr/bin/nvidia-uninstall ]; then nvidia-uninstall --silent || true; fi\n'
    if family == "arch":
        return common + (
            "pacman -Qq 2>/dev/null | grep -E '^(nvidia|lib32-nvidia|opencl-nvidia)'"
            " | xargs -r pacman -Rns --noconfirm || true\ntrue"
        )
    if family == "fedora":
        return common + (
            "dnf -y remove '*nvidia*' --exclude='nvidia-gpu-firmware' || true\ntrue"
        )
    if family == "suse":
        # Package list per the official openSUSE removal procedure, extended
        # with x11-video-nvidiaG0X — the userspace name of the old G04/G05
        # generations, which does not start with "nvidia". zypper rm
        # additionally cleans up dependencies. kernel-firmware-nvidia (nouveau
        # GSP firmware) matches none of the patterns, so it stays installed.
        # --qf '%{NAME}': zypper takes a capability (NAME[.ARCH][OP EDITION]),
        # never a whole rpm -qa line with version and architecture glued on —
        # those match no package and the removal silently does nothing.
        return common + (
            # a lock from an earlier .run installation blocks the removal of
            # the very packages it covers — lift it first, and do not leave it
            # behind on a system that no longer has the driver
            _SUSE_REMOVE_LOCKS + "\n"
            "rpm -qa --qf '%{NAME}\\n'"
            " | grep -E '^(nvidia|libnvidia|x11-video-nvidia)'"
            " | grep -v container"
            " | xargs -r zypper -n rm || true\ntrue"
        )
    # debian / ubuntu / mint
    return common + (
        "dpkg -l | awk '/^ii/ && $2 ~ /nvidia/ {print $2}' | grep -v firmware"
        " | xargs -r apt-get -y purge || true\n"
        "apt-get -y autoremove || true\ntrue"
    )


def _initramfs_step(distro: DistroInfo) -> tuple[str, str]:
    """initramfs update step using the command specific to the distribution."""
    return (
        "Aktualizacja initramfs",
        f'{distro.initramfs_cmd} || error "Aktualizacja initramfs nie powiodła się"',
    )


# ---------------------------------------------------------------------------
# Steps for the individual installation methods
# ---------------------------------------------------------------------------

def _steps_repo(opts: InstallOptions, keyring: str = "") -> list[tuple[str, str]]:
    """Installation from the distribution repository (or the official NVIDIA repo)."""
    fam = opts.distro.family
    steps: list[tuple[str, str]] = []

    # The .run-file driver must be removed BEFORE installing packages.
    # Otherwise distribution mechanisms (e.g. nvidia-installer-cleanup on
    # Ubuntu) will fire nvidia-uninstall during unpacking and delete files
    # that the packages have just installed (including glvnd 10_nvidia.json),
    # causing the desktop to fall back to CPU software rendering.
    steps.append((
        "Usuwanie sterownika z pliku .run (jeśli obecny)",
        "if [ -x /usr/bin/nvidia-uninstall ]; then"
        " nvidia-uninstall --silent || true; fi\n"
        # a lock left by an earlier .run installation would make the packages
        # below uninstallable — the card goes back to packages, so it goes
        + (_SUSE_REMOVE_LOCKS + "\n" if fam == "suse" else "")
        + "true",
    ))

    if fam == "arch":
        pkg = "nvidia-open-dkms" if opts.open_modules else "nvidia-dkms"
        steps.append((
            "Usuwanie konfliktującej odmiany sterownika",
            "for p in nvidia nvidia-lts nvidia-open nvidia-open-dkms nvidia-dkms; do\n"
            '  pacman -Qq "$p" >/dev/null 2>&1 && pacman -Rdd --noconfirm "$p"\n'
            "done; true",
        ))
        steps.append((
            "Instalacja sterownika z repozytorium (pełna aktualizacja systemu)",
            f"{_ARCH_KERNEL_HEADERS}\n"
            f"pacman -Syu --noconfirm --needed {pkg} nvidia-utils nvidia-settings"
            ' "${KERNEL_PKG}-headers"'
            ' || error "Instalacja pakietów nie powiodła się"',
        ))
        steps.append((
            "Kontrola integralności pakietów EGL (naprawa brakujących plików)",
            _ARCH_VERIFY_EGL_PACKAGES,
        ))

    elif fam == "fedora":
        # RPMFusion only when no enabled repository already provides
        # akmod-nvidia — distributions with their own driver repo
        # (e.g. Nobara) keep theirs, plain Fedora gets RPMFusion
        steps.append((
            "Włączanie repozytorium RPMFusion (free + nonfree)",
            "if dnf -q repoquery --qf '%{name}\\n' akmod-nvidia 2>/dev/null | grep -q .; then\n"
            '  echo "A repository with the NVIDIA driver is already available — skipping RPMFusion"\n'
            "else\n"
            '  dnf -y install'
            ' "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm"'
            ' "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm"'
            " || true\nfi\ntrue",
        ))
        if opts.open_modules:
            # RPMFusion macro switching akmod-nvidia to open modules;
            # it must exist before akmods builds the module
            steps.append((
                "Włączanie otwartych modułów jądra (makro RPMFusion)",
                "printf '%%_with_kmod_nvidia_open 1\\n' > /etc/rpm/macros.nvidia-kmod"
                ' || error "Nie udało się zapisać makra RPM"',
            ))
        steps.append((
            "Instalacja sterownika (akmod-nvidia)",
            _FEDORA_REPO_INSTALL,
        ))
        steps.append((
            "Budowanie modułu jądra (akmods — może potrwać kilka minut)",
            'akmods --force || error "Budowanie modułu jądra nie powiodło się"',
        ))

    elif fam == "suse":
        # The official NVIDIA repository provides the userspace packages
        # (nvidia-video-G0X); added only when no repo points at it yet —
        # a system with the repo already configured is left untouched.
        repo_url = nvidia_versions.suse_repo_url(opts.distro)
        steps.append((
            "Dodawanie repozytorium NVIDIA (zypper)",
            # Three states, not two: the repository can be missing, present and
            # enabled, or present but DISABLED. `zypper lr` lists disabled ones
            # too, so testing for the URL alone would treat a disabled repo as
            # ready — and the installation would then fail on packages nothing
            # provides. A disabled NVIDIA repo is a real setup: it is what you
            # switch off to keep a system update from pulling the driver in by
            # itself (openSUSE installs it via modalias supplements).
            'NV_ALIAS="$(zypper -n lr -u 2>/dev/null'
            " | awk -F'|' '/download\\.nvidia\\.com\\/opensuse/"
            ' {gsub(/^ +| +$/,"",$2); print $2; exit}\')"\n'
            'if [ -z "$NV_ALIAS" ]; then\n'
            f"  zypper -n ar -f '{repo_url}' NVIDIA"
            ' || error "Dodawanie repozytorium NVIDIA nie powiodło się"\n'
            "elif ! zypper -n lr -u -E 2>/dev/null"
            " | grep -q 'download.nvidia.com/opensuse'; then\n"
            '  echo "The NVIDIA repository is disabled — enabling it ($NV_ALIAS)"\n'
            '  zypper -n mr -e "$NV_ALIAS"'
            ' || error "Włączenie repozytorium NVIDIA nie powiodło się"\n'
            "fi\n"
            "zypper -n --gpg-auto-import-keys refresh"
            ' || error "Odświeżanie repozytoriów nie powiodło się"',
        ))
        steps.append((
            "Instalacja sterownika z repozytorium (zypper)",
            _suse_repo_install(opts.open_modules,
                               _suse_generations(opts.gpu_name,
                                                 opts.gpu_pci_id)),
        ))

    else:  # debian family
        if opts.distro.ubuntu_based:
            pkg = opts.repo_package or "nvidia-driver-580"
            steps.append((
                "Odświeżanie listy pakietów",
                'apt-get update || error "apt-get update nie powiodło się"',
            ))
            steps.append((
                f"Instalacja sterownika ({pkg})",
                f'apt-get -y install {pkg} || error "Instalacja pakietu nie powiodła się ({pkg})"',
            ))
        elif opts.repo_source == "nvidia":
            # Plain Debian, the official NVIDIA repository — the only package
            # source for RTX 50xx cards (the Debian repo ends at 550).
            # Debian and NVIDIA packages must not mix, hence the cleanup.
            pkg = "nvidia-open" if opts.open_modules else "cuda-drivers"
            steps.append((
                "Odinstalowanie sterownika z repozytorium Debiana (jeśli obecny)",
                _removal_commands("debian"),
            ))
            steps.append((
                "Dodawanie oficjalnego repozytorium NVIDIA (cuda-keyring)",
                f'apt-get -y install "{keyring}"'
                ' || error "Instalacja pakietu cuda-keyring nie powiodła się"\n'
                'apt-get update || error "apt-get update nie powiodło się"',
            ))
            steps.append((
                f"Instalacja sterownika z repozytorium NVIDIA ({pkg})",
                f"apt-get -y install linux-headers-amd64 {pkg}"
                f' || error "Instalacja pakietu nie powiodła się ({pkg})"',
            ))
        else:
            steps.append((
                "Odinstalowanie sterownika z repozytorium NVIDIA (jeśli obecny)",
                _removal_commands("debian") + "\n" + _REMOVE_NVIDIA_REPO,
            ))
            steps.append((
                "Włączanie sekcji contrib / non-free / non-free-firmware",
                # Debian may use the classic sources.list or the deb822 format
                _DEBIAN_NONFREE_SECTIONS,
            ))
            steps.append((
                "Instalacja sterownika (nvidia-driver)",
                "apt-get -y install nvidia-driver firmware-misc-nonfree"
                " linux-headers-amd64"
                ' || error "Instalacja pakietów nie powiodła się"',
            ))

    # Common configuration after installing from the repository
    steps.append(("Konfiguracja modprobe (blokada nouveau, modeset)", _MODPROBE_CONFIG))
    steps.append(_initramfs_step(opts.distro))
    return steps


def _steps_nvk(opts: InstallOptions) -> list[tuple[str, str]]:
    """Switching to the open NVK / Mesa driver (nouveau)."""
    fam = opts.distro.family
    extra: list[tuple[str, str]] = []  # extra steps depending on the distribution
    if fam == "arch":
        install = (
            "pacman -Syu --noconfirm --needed mesa vulkan-nouveau vulkan-icd-loader"
            ' vulkan-tools || error "Instalacja pakietów Mesa nie powiodła się"'
        )
        firmware = (
            "pacman -S --noconfirm --needed linux-firmware"
            ' || error "Instalacja pakietu linux-firmware nie powiodła się"'
        )
    elif fam == "fedora":
        extra.append((
            "Uzupełnianie modułu nouveau (pakiet kernel-modules)",
            _NOUVEAU_KERNEL_MODULES_FEDORA,
        ))
        install = (
            "dnf -y install mesa-vulkan-drivers mesa-dri-drivers vulkan-tools"
            ' || error "Instalacja pakietów Mesa nie powiodła się"'
        )
        firmware = (
            "dnf -y install nvidia-gpu-firmware"
            ' || error "Instalacja pakietu nvidia-gpu-firmware nie powiodła się"'
        )
    elif fam == "suse":
        # The NVK Vulkan driver (libvulkan_nouveau) exists in Tumbleweed;
        # older Leap releases ship a Mesa without it — then only the warning
        # fires and the desktop still runs on nouveau OpenGL.
        install = (
            "zypper -n in Mesa Mesa-dri libvulkan1 vulkan-tools"
            ' || error "Instalacja pakietów Mesa nie powiodła się"\n'
            "if zypper -n se -x -t package libvulkan_nouveau >/dev/null 2>&1; then\n"
            "  zypper -n in libvulkan_nouveau"
            ' || error "Instalacja pakietu nie powiodła się (libvulkan_nouveau)"\n'
            "else\n"
            '  echo "WARNING: the libvulkan_nouveau (NVK) package is not available'
            ' in the repositories — only OpenGL (nouveau) will work"\n'
            "fi"
        )
        firmware = (
            "zypper -n in kernel-firmware-nvidia"
            ' || error "Instalacja pakietu nie powiodła się (kernel-firmware-nvidia)"'
        )
    elif opts.use_backports and not opts.distro.ubuntu_based:
        # Plain Debian with an RTX 50xx (Blackwell) card: the stable release is
        # too old in three places at once — the kernel (nouveau without GB20x),
        # Mesa < 25.2 (NVK without Blackwell) and firmware without GSP r570.
        # All three components come from the official backports.
        extra.append((
            "Włączanie oficjalnych backportów Debiana",
            ". /etc/os-release\n"
            'BP="${VERSION_CODENAME}-backports"\n'
            'if ! apt-cache policy | grep -q "$BP"; then\n'
            '  echo "deb http://deb.debian.org/debian ${BP} main contrib'
            ' non-free non-free-firmware"'
            " > /etc/apt/sources.list.d/nvidia-installer-backports.list\n"
            "fi\n" + _DEBIAN_NONFREE_SECTIONS,
        ))
        extra.append((
            "Instalacja nowszego jądra z backportów (wymagane dla RTX 50xx)",
            'apt-get -y -t "$BP" install linux-image-amd64'
            ' || error "Instalacja jądra z backportów nie powiodła się"',
        ))
        # libgl1-mesa-dri from the same version as the Vulkan driver —
        # mixing Mesa versions (GL 25.0 + Vulkan 25.2) breaks the desktop
        install = (
            'apt-get -y -t "$BP" install mesa-vulkan-drivers libgl1-mesa-dri'
            " mesa-utils vulkan-tools"
            ' || error "Instalacja pakietów Mesa z backportów nie powiodła się"'
        )
        firmware = (
            'apt-get -y -t "$BP" install firmware-nouveau'
            ' || apt-get -y -t "$BP" install firmware-misc-nonfree'
            ' || error "Instalacja firmware nouveau nie powiodła się"'
        )
    else:
        install = (
            "apt-get update || true\n"
            "apt-get -y install mesa-vulkan-drivers mesa-utils vulkan-tools"
            ' || error "Instalacja pakietów Mesa nie powiodła się"'
        )
        if opts.distro.ubuntu_based:
            firmware = (
                "apt-get -y install linux-firmware"
                ' || error "Instalacja pakietu linux-firmware nie powiodła się"'
            )
        else:
            # Plain Debian: nouveau firmware lives in the non-free-firmware section;
            # older releases don't know the firmware-nouveau package
            firmware = (
                _DEBIAN_NONFREE_SECTIONS + "\n"
                "apt-get -y install firmware-nouveau"
                " || apt-get -y install firmware-misc-nonfree"
                ' || error "Instalacja firmware nouveau nie powiodła się"'
            )
    return [
        ("Odinstalowanie sterownika NVIDIA (jeśli obecny)", _removal_commands(fam)),
        ("Usuwanie blokady nouveau i konfiguracji NVIDIA", _REMOVE_MODPROBE_CONFIG),
        ("Usuwanie wymuszeń NVIDIA w zmiennych środowiskowych", _REMOVE_GL_ENV),
        ("Usuwanie parametrów nvidia-drm z konfiguracji GRUB", _REMOVE_KERNEL_PARAMS),
        *extra,
        ("Instalacja sterownika NVK / Mesa", install),
        (
            "Instalacja firmware GPU (GSP — wymagany na kartach RTX)",
            firmware + "\n" + _GSP_FIRMWARE_CHECK + "\n" + _NOUVEAU_MODULE_CHECK,
        ),
        _initramfs_step(opts.distro),
    ]


def _steps_run(opts: InstallOptions, runfile: str) -> list[tuple[str, str]]:
    """Installation from a downloaded NVIDIA .run file."""
    fam = opts.distro.family
    if fam == "arch":
        deps = (
            f"{_ARCH_KERNEL_HEADERS}\n"
            "pacman -Syu --noconfirm --needed base-devel dkms"
            ' "${KERNEL_PKG}-headers"'
            ' || error "Instalacja zależności nie powiodła się"'
        )
    elif fam == "fedora":
        deps = (
            "dnf -y install gcc make dkms kernel-devel kernel-headers"
            " libglvnd-devel libglvnd-glx libglvnd-opengl"
            ' || error "Instalacja zależności nie powiodła się"'
        )
    elif fam == "suse":
        # Kernel headers match the running kernel's flavor (default / longterm
        # etc. — the suffix of uname -r). dkms is missing from some Leap
        # releases' repositories: then the .run installer builds the module
        # only for the running kernel (NV_DKMS_FLAG stays empty) instead of
        # failing the whole installation; _DKMS_ALL_KERNELS degrades to
        # warnings the same way.
        deps = (
            "zypper -n --gpg-auto-import-keys refresh || true\n"
            "zypper -n in gcc make libglvnd-devel pkg-config"
            ' || error "Instalacja zależności nie powiodła się"\n'
            'FLAVOR="$(uname -r)"; FLAVOR="${FLAVOR##*-}"\n'
            'zypper -n in "kernel-${FLAVOR}-devel"'
            " || zypper -n in kernel-default-devel"
            ' || error "Instalacja nagłówków jądra nie powiodła się"\n'
            'NV_DKMS_FLAG="--dkms"\n'
            "command -v dkms >/dev/null 2>&1 || zypper -n in dkms || true\n"
            "if ! command -v dkms >/dev/null 2>&1; then\n"
            '  echo "WARNING: the dkms package is unavailable — the module will'
            ' be built only for the running kernel"\n'
            '  NV_DKMS_FLAG=""\n'
            "fi"
        )
    else:
        deps = (
            'apt-get update || error "apt-get update nie powiodło się"\n'
            'apt-get -y install build-essential dkms "linux-headers-$(uname -r)"'
            " libglvnd-dev pkg-config"
            ' || error "Instalacja zależności nie powiodła się"'
        )

    # Open-modules flag depending on the driver version
    open_flag = (
        nvidia_versions.open_module_flag(opts.run_version) if opts.open_modules else ""
    )
    # suse: --dkms only when dkms is actually available (the deps step above
    # sets NV_DKMS_FLAG); other families keep the literal flag — plans unchanged
    dkms_flag = "$NV_DKMS_FLAG" if fam == "suse" else "--dkms"
    # A loaded nvidia module (.run installation with the driver running,
    # e.g. changing the version from a repository driver): the 595.84 installer
    # then asks to skip the check and in --silent mode ABORTS by default
    # ("Answer: Abort installation" — the EndeavourOS 2026-07-05 case).
    # Consent is given upfront with --allow-installation-with-running-driver;
    # older installers (including Legacy branches) don't know this flag, so the
    # condition checks the actual state (the module in /proc/modules) AND the
    # installer's capabilities (the flag in --advanced-options). With the nvidia
    # module inactive — the nouveau/NVK path, on which previous cycles passed —
    # the variable stays empty and the command is as before.
    allow_running = (
        'NV_ALLOW_RUNNING=""\n'
        "if grep -q '^nvidia ' /proc/modules"
        f' && sh "{runfile}" --advanced-options 2>/dev/null'
        " | grep -q -- --allow-installation-with-running-driver; then\n"
        '  echo "The nvidia module is loaded — passing the installer consent'
        ' to install with the driver running"\n'
        '  NV_ALLOW_RUNNING="--allow-installation-with-running-driver"\n'
        "fi"
    )
    return [
        ("Instalacja zależności do budowania modułu jądra", deps),
        ("Odinstalowanie poprzednich sterowników", _removal_commands(fam)),
        ("Konfiguracja modprobe (blokada nouveau, modeset)", _MODPROBE_CONFIG),
        (
            "Instalacja sterownika NVIDIA z pliku .run (może potrwać kilka minut)",
            # The installation happens from a running desktop, so nouveau (or
            # the old nvidia module) still holds the card: --no-nouveau-check
            # then doesn't abort the installation, and --skip-module-load skips
            # the trial module load, which would fail. The nouveau blacklist is
            # already written, so after a restart nvidia will claim the card.
            _LLVM_KERNEL_ENV + "\n" + allow_running + "\n"
            f'env $NV_TOOLCHAIN_ENV sh "{runfile}" --silent --accept-license {dkms_flag} --no-x-check'
            f' --no-nouveau-check --skip-module-load $NV_ALLOW_RUNNING{open_flag}'
            ' || error "Instalator NVIDIA zwrócił błąd — szczegóły w /var/log/nvidia-installer.log"',
        ),
        ("Budowanie modułu DKMS dla pozostałych jąder", _DKMS_ALL_KERNELS),
    ] + ([(
        # only openSUSE pulls the driver in by itself on an update — see the
        # comment at _SUSE_LOCK_PATTERNS
        "Blokada pakietów NVIDIA w zypperze (ochrona instalacji .run)",
        _SUSE_ADD_LOCKS,
    )] if fam == "suse" else []) + [
        _initramfs_step(opts.distro),
    ]


def build_plan(
    opts: InstallOptions, runfile: str = "", keyring: str = ""
) -> tuple[list[str], str]:
    """Builds the installation plan: (list of step labels, bash script content)."""
    if opts.method == "repo":
        steps = _steps_repo(opts, keyring)
    elif opts.method == "nvk":
        steps = _steps_nvk(opts)
    elif opts.method == "run":
        steps = _steps_run(opts, runfile)
    else:
        raise ValueError(f"Nieznana metoda instalacji: {opts.method}")

    # A common, purely diagnostic step at the end of every method — see the
    # comment near _BOOT_REPORT_STEP. Opt-in: when the option is disabled the
    # installation cleans up the service from earlier installations.
    steps.append(_BOOT_REPORT_STEP if opts.boot_report else _BOOT_REPORT_REMOVE_STEP)

    # Optional Timeshift snapshot as the very first step — see _SNAPSHOT_STEP.
    # Off by default (opts.snapshot=False), so existing plans stay unchanged.
    if opts.snapshot:
        steps.insert(0, _SNAPSHOT_STEP)

    lines = [_SCRIPT_HEADER]
    for label, cmds in steps:
        lines.append(f'step "{label}"')
        lines.append(cmds)
    lines.append('echo "@SUCCESS@"')
    return [s[0] for s in steps], "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Thread that runs the installation (download + script via pkexec)
# ---------------------------------------------------------------------------

class InstallThread(QThread):
    """Runs the whole installation in the background, reporting progress via Qt signals."""

    sig_log = Signal(str)            # next log line
    sig_step = Signal(int, int, str)  # step number, step count, label
    sig_download = Signal(int)       # .run file download percentage
    sig_finished = Signal(bool, str)  # success?, final message

    def __init__(self, opts: InstallOptions, sudo_password: str = "", parent=None):
        super().__init__(parent)
        self.opts = opts
        # Fallback when the system has no pkexec: password for sudo -S,
        # fetched and verified earlier by the GUI (never goes to the logs)
        self._sudo_password = sudo_password

    # ---- downloading the .run file ---------------------------------------
    def _verify_runfile(self, path: str) -> bool:
        """Checks the .run installer's built-in checksum (without root).

        Catches files truncated during download (e.g. a hard kill of the
        program leaves a > 50 MB file in the cache that looks complete)
        as well as ones corrupted or swapped along the way.
        """
        self.sig_log.emit(tr("Sprawdzanie integralności pliku .run..."))
        code, _, _ = utils.run(["sh", path, "--check"], timeout=300)
        return code == 0

    def _download_runfile(self) -> str:
        """Downloads the .run file to the cache; returns the file path."""
        import requests

        ver = self.opts.run_version
        url = nvidia_versions.download_url(ver)
        dest = utils.CACHE_DIR / f"NVIDIA-Linux-x86_64-{ver}.run"

        # File already downloaded earlier — use the copy if it passes the check
        if dest.exists() and dest.stat().st_size > 50_000_000:
            if self._verify_runfile(str(dest)):
                self.sig_log.emit(
                    tr("Plik {n} już pobrany — używam kopii lokalnej")
                    .format(n=dest.name)
                )
                self.sig_download.emit(100)
                return str(dest)
            self.sig_log.emit(tr("Kopia lokalna uszkodzona — pobieram ponownie"))
            dest.unlink(missing_ok=True)

        self.sig_log.emit(tr("Pobieranie:") + f" {url}")
        try:
            r = requests.get(
                url,
                stream=True,
                timeout=60,
                headers={"User-Agent": "Mozilla/5.0 (nvidia-installer-gui)"},
            )
            r.raise_for_status()
            total = int(r.headers.get("content-length", 0))
            done = 0
            with open(dest, "wb") as f:
                for chunk in r.iter_content(chunk_size=256 * 1024):
                    f.write(chunk)
                    done += len(chunk)
                    if total:
                        self.sig_download.emit(int(done * 100 / total))
        except Exception:
            # We don't leave an incomplete file in the cache
            dest.unlink(missing_ok=True)
            raise
        if not self._verify_runfile(str(dest)):
            dest.unlink(missing_ok=True)
            raise RuntimeError(
                tr("Pobrany plik .run nie przechodzi kontroli integralności"
                   " — spróbuj ponownie")
            )
        self.sig_log.emit(
            tr("Pobrano:") + f" {dest} ({dest.stat().st_size // (1024*1024)} MB)"
        )
        return str(dest)

    def _download_keyring(self) -> str:
        """Downloads the cuda-keyring package (NVIDIA repo); returns the file path."""
        import requests

        url = nvidia_versions.keyring_url(self.opts.distro)
        dest = utils.CACHE_DIR / url.rsplit("/", 1)[-1]
        if dest.exists() and dest.stat().st_size > 1000:
            self.sig_log.emit(
                tr("Plik {n} już pobrany — używam kopii lokalnej").format(n=dest.name)
            )
            return str(dest)
        self.sig_log.emit(tr("Pobieranie:") + f" {url}")
        try:
            r = requests.get(
                url,
                timeout=60,
                headers={"User-Agent": "Mozilla/5.0 (nvidia-installer-gui)"},
            )
            r.raise_for_status()
            dest.write_bytes(r.content)
        except Exception:
            dest.unlink(missing_ok=True)
            raise
        return str(dest)

    # ---- the thread's main work ------------------------------------------
    def run(self):  # noqa: D102 — QThread method
        log_lines: list[str] = []

        def log(text: str) -> None:
            log_lines.append(text)
            self.sig_log.emit(text)

        ok = False
        err_msg = ""
        try:
            if not utils.is_linux():
                raise RuntimeError(tr("Instalacja działa tylko na Linuksie"))
            use_sudo = False
            if not utils.which("pkexec"):
                # Fallback path without polkit: sudo with the password from the GUI
                if utils.which("sudo") and self._sudo_password:
                    use_sudo = True
                else:
                    raise RuntimeError(
                        tr("Brak poleceń pkexec i sudo — zainstaluj pakiet pkexec"
                           " (polkit) lub sudo")
                    )

            # 1. The .run method requires downloading the installer first,
            #    and the NVIDIA repo on Debian — the cuda-keyring package
            runfile = keyring = ""
            if self.opts.method == "run":
                log(tr("Wersja sterownika:") + f" {self.opts.run_version}")
                runfile = self._download_runfile()
            elif self.opts.method == "repo" and self.opts.repo_source == "nvidia":
                keyring = self._download_keyring()

            # 2. Generate the installation script
            steps, script = build_plan(self.opts, runfile, keyring)
            log(tr("Liczba kroków:") + f" {len(steps)}")

            # 3. Run as root — a single password prompt.
            #    Normally pkexec (the polkit window): the script goes through a
            #    pipe straight to root (_ROOT_RUNNER), without a file in /tmp
            #    whose content another process could swap before execution.
            #    Fallback sudo -S: the pipe carries the password (-p "" disables
            #    the text prompt), so the script must go via a temporary file —
            #    a path tested on Debian without polkit, kept.
            if use_sudo:
                with tempfile.NamedTemporaryFile(
                    "w", suffix=".sh", prefix="nvidia-installer-",
                    delete=False, encoding="utf-8",
                ) as f:
                    f.write(script)
                    script_path = f.name
                os.chmod(script_path, 0o700)
                log(tr("Skrypt instalacyjny:") + f" {script_path}")
                cmd = ["sudo", "-S", "-k", "-p", "", "bash", script_path]
            else:
                log(tr("Skrypt instalacyjny przekazany potokiem (bez pliku w /tmp)"))
                cmd = ["pkexec", "bash", "-c", _ROOT_RUNNER]
            proc = subprocess.Popen(
                cmd,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                bufsize=1,
            )
            if use_sudo:
                proc.stdin.write(self._sudo_password + "\n")
                proc.stdin.flush()
                proc.stdin.close()
            else:
                # The script fits in the pipe buffer — the write won't block
                # the thread even while the polkit authorization window awaits the password
                proc.stdin.write(script)
                proc.stdin.close()
            idx = 0
            success_marker = False
            for line in proc.stdout:
                line = line.rstrip("\n")
                if line.startswith("@STEP@"):
                    idx += 1
                    label = line[len("@STEP@"):].strip()
                    self.sig_step.emit(idx, len(steps), label)
                    # Translate the marker for the log (the step indicator is
                    # translated separately in the GUI via tr_prefix)
                    line = "@STEP@ " + tr_prefix(label)
                elif line.startswith("@ERROR@"):
                    # Error text goes both to the log and the final dialog,
                    # translated to the interface language
                    err_msg = tr_prefix(line[len("@ERROR@"):].strip())
                    line = "@ERROR@ " + err_msg
                elif line.strip() == "@SUCCESS@":
                    success_marker = True
                log(line)
            code = proc.wait()
            ok = code == 0 and success_marker

            if not ok and not err_msg:
                if code in (126, 127):
                    err_msg = tr("Anulowano autoryzację administratora (pkexec)")
                else:
                    err_msg = tr("Skrypt zakończył się kodem") + f" {code}"
        except Exception as e:
            err_msg = str(e)
            log(tr("BŁĄD:") + f" {err_msg}")

        # 4. Add an installation history entry with the full log
        wersja = (
            self.opts.run_version
            or self.opts.repo_package
            or ("NVK / Mesa" if self.opts.method == "nvk"
                else "repozytorium NVIDIA" if self.opts.repo_source == "nvidia"
                else "repozytorium")
        )
        try:
            history.add_entry(
                metoda=self.opts.method,
                wersja=wersja,
                dystrybucja=self.opts.distro.name,
                status="sukces" if ok else "błąd",
                log_text="\n".join(log_lines),
            )
        except Exception:
            pass  # a history-write problem must not ruin the result

        self.sig_finished.emit(ok, err_msg)
